# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
  - index.md
  - will.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: hacker
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
